Adding nodelabel checks for validation (#363)
Adds a new **NodeLabelsRule** to validate that all cluster nodes have
**kubernetes.io/arch=ppc64le** and **node.openshift.io/os_id=rhel** and
ensures at least one worker node exists.

Successful run 
```powershell
abhishek-kushwaha@DESKTOP-4A3B6H3:~/orchestration-ai-services/ai-services/bin$ sudo KUBECONFIG=/home/abhishek-kushwaha/.kube/config ./ai-services bootstrap validate --runtime openshift
Running bootstrap validation...
✔ Operators installed
  - Secondary Scheduler Operator installed
  - Cert-Manager Operator installed
  - Service Mesh 3 Operator installed
  - Node Feature Discovery Operator installed
  - RHOAI Operator installed
✔ Node labels validated for ppc arch and rhel os
All validations passed
``` 

Unsuccessful run 
```powershell
abhishek-kushwaha@DESKTOP-4A3B6H3:~/orchestration-ai-services/ai-services/bin$ sudo KUBECONFIG=/home/abhishek-kushwaha/.kube/config ./ai-services bootstrap validate --runtime openshift
[sudo] password for abhishek-kushwaha: 
Running bootstrap validation...
✖ failed to list ClusterServiceVersions: failed to get server groups: the server has asked for the client to provide credentials
HINT: This tool requires certain operators to be up and running, please run `ai-services bootstrap configure` to install required operators
✖ failed to list cluster nodes: failed to get server groups: the server has asked for the client to provide credentials
HINT: Ensure all nodes have kubernetes.io/arch=ppc64le and node.openshift.io/os_id=rhel
Please refer to troubleshooting guide for more information: https://www.ibm.com/docs/aiservices?topic=services-troubleshooting
Error: bootstrap validation failed: 2 validation check(s) failed
```

---------

Signed-off-by: Abhishek-Kushwaha <Abhishek.Kushwaha@ibm.com>
Signed-off-by: Abhishek Kushwaha <Abhishek.Kushwaha@ibm.com>